#+TITLE: The Rise of Savea
#+author: Braden Rice
You are from a land of great peace and prosperity. The many kingdoms have peace and open trade.
There are great highways where anyone can travel safely without fear of monsters.
The only real frontier is the great seas. King Tridon of Maricia sent several
peaceful expiditions out to find other peoples and kingdoms, sure that the world
was more than just this land.

None of them ever returned until one single survivor made it back on a lifeboat.
Upon his return, he informed the king that they had been attacked by a dragon
turtle. If they were to continue their exploratory efforts, they would need
a stronger ship with great warriors.

King Tridon sent word to every kingdom. He told them of great sea monsters,
but also of adventure in new lands and maybe even great treasure.

You adventurers have responded to that call...
* Savea
** who
  Savea is a Dracolich. He resides deep within a volcanic cave on the island of Falealupo.
  The path to it is lined with deamons waiting to kill any living mortals who attempt to enter his domain.
** his servants
  His immediate servants are Succubus and Incubus but he also employs various other undead monsters to go about his bidding.
** his goals
True immortality and  dominioin over the Tialoan Islands
*** how
    collecting some powerful set of objects
     - Hauone (sands of life)
** his cult
  The Tarako is the cult of Maliu mages who created savea from an ancient red dragon who wanted to cheat death so that
  he could subtly and quietly obtain dominion over the [islandy name] islands
*** his servants
  His immediate servants are Succubus and Incubus but he also employs various other undead monsters to go about his bidding.
* Week 1: Introduce the Tialoan Islands
* Week 2: The Gold Volcano (drop hints about unexplained maliu magic (necromancy))
* Week 3*: The Night Marchers
** Myth
  [[https://www.to-hawaii.com/legends/night-marchers.php][night marchers]]
* Week 4
* Week 5
* Week 6*
* Week 7
* Week 8
* Week 9*
* Week 10
* Week 11
* Week 12*
