#+TITLE: Aurus
#+LANGUAGE: en
#+OPTIONS: H:4 num:nil toc:nil \n:nil @:t ::t |:t ^:t *:t TeX:t LaTeX:t
#+OPTIONS: html-postamble:nil
#+STARTUP: showeverything entitiespretty
#+SETUPFILE: ./theme-bigblow.setup
* Character
** IDENTIFICATION
| CLASS & LEVEL  | BACKGROUND | PLAYER NAME | RACE                      | ALIGNMENT    |
|----------------+------------+-------------+---------------------------+--------------|
| Level 2 Ranger | Outlander  | Braden      | Centaur half brass dragon | Chaotic good |
- [ ] INSPIRATION
** PERSONALITY TRAITS
   - I watch over my friends as if they were a litter of newborn pups.
   - I feel far more comfortable around animals than people.
** IDEALS
   - Live and Let Live. Meddling in the affairs of others only causes trouble. (Neutral)
** BONDS
   - My family, clan, or tribe is the most important thing in my life, even when they are far from me.
** FLAWS
   - I will never be accepted by pure centaurs. They will always hate, fear, shun and reject me.
** HEALTH & ARMOR
| ARMOR CLASS | INITIATIVE | LAND SPEED | AIR SPEED |
|-------------+------------+------------+-----------|
|          30 |          4 |         50 |       100 |

| CURRENT HP | MAX HP |
|------------+--------|
|         69 |     69 |

| TEMP CURRENT HP |   |

| HIT DICE | 5d12 |
*** DEATH SAVES
**** SUCCESSES
     - [ ]
     - [ ]
     - [ ]
**** FAILURES
     - [ ]
     - [ ]
     - [ ]
** STATS
   |     | STRENGTH | DEXTERITY | CONSTITUTION | INTELLIGENCE | WISDOM | CHARISMA |
   |-----+----------+-----------+--------------+--------------+--------+----------|
   | VAL |       23 |        19 |           18 |            8 |     16 |       12 |
   | MOD |       +6 |        +4 |           +4 |           -1 |     +3 |       +1 |
** THROWS *-4 hide +4 grapple*
   | +2 | PROFICIENCY BONUS |

   | \check | +8 | Strength     |
   | \check | +6 | Dexterity    |
   |   | +4 | Constitution |
   |   | -1 | Intelligence |
   |   | +3 | Wisdom       |
   |   | +1 | Charisma     |

   |   | +6 | Acrobatics (dex)     |
   | \check | +3 | Animal Handling (wis) |
   |   | -1 | Arcana (int)          |
   | \check | +8 | Athletics (str)       |
   |   | +1 | Deception (cha)       |
   |   | -1 | History (int)         |
   | \check | +3 | Insight (wis)         |
   |   | +1 | Intimidation (cha)    |
   |   | -1 | Investigation(int)    |
   |   | +3 | Medicine (wis)        |
   |   | -1 | Nature (int)          |
   | \check | +3 | Perception (wis)      |
   |   | +1 | Performance (cha)     |
   |   | -1 | Persuasion (int)      |
   |   | -1 | Religion (int)        |
   |   | +6 | Slight of Hand (dex)  |
   |   | +2 | Stealth (dex)         |
   | \check | +3 | Survival (wis)        |

   | 13 | PASSIVE WISDOM (PERCEPTION) |
** ATTACKS & SPELLCASTING
   - *-1 penalty on all attack rolls*
   - +2 on attack rolls with ranged weapons
*** Spells (wisdom)
   - Spell save DC
     - 13
   - Spell attack mod
     - 5
   - Spell Slots
     - 1st level
       - [ ]
       - [ ]
   - [ ] Hail of Thorns [[elisp:(nd10 1)][1d10]]
   - [ ] Hunter's Mark :target
*** Claws x2 (secondary attack)
    - [[elisp:(list (nd20 1) (nd6 1))][1d6]]
*** Bite (secondary attack)
    - [[elisp:(list (nd20 1) (nd8 1))][1d8]]
*** Breath Weapon 60ft line of fire
    - [[elisp:(list (nd20 1) (list (apply '+ (nd8 6))))][6d8]]
    - Save 18 reduces damage by half
*** longsword
    - [[elisp:(list (nd20 1) (nd8 1))][1d8 slashing]]
    - [[elisp:(list (nd20 1) (nd10 1))][versatile (1d10)]]
*** longbow
    - [[elisp:(list (nd20 1) (nd8 1))][1d8 piercing]]
    - range 150/600
    - heavy
    - two-handed
*** deal 2x damage with a lance when they charge
** FEATURES & TRAITS
*** Favored enemy *Dragons*
    - Advantage on Wisdom (survival) checks to track
    - Advantage on intelligence checks to recall information about them
*** Natural Explorer *Forest*
    - When you make an Intelligence or Wisdom check related to your
    favored terrain, your proficiency bonus is doubled if you are
    using a skill that you’re proficient in.
    - Difficult terrain doesn’t slow your group’s travel
    - Your group can’t become lost except by magical means.
    - Even when you are engaged in another activity while traveling
    (such as foraging, navigating, or tracking), you remain alert to danger.
    - If you are traveling alone, you can move stealthily at a normal pace.
    - When you forage, you find twice as much food as you normally would.
    - While tracking other creatures, you also learn their exact number,
    their sizes, and how long ago they passed through the area.
*** Darkvision 60ft
*** low-light vision
*** Immunities
    - Sleep effects
    - Paralisis effects
    - Fire
*** Wanderer
    - Excelent memory for maps and geography
    - Can find food and fresh water for yoursel and 5 others each day
*** Fighting Style *Archery*
    +2 bonus to attack rollw made with ranged weapons
** EQUIPMENT
   | CP |   |
   | SP |   |
   | EP |   |
   | GP |   |
   | PP |   |

   - Scale Mail *14 + DexMod (max +2)*
   - Long sword
   - Longbow
   - Dungeoneer's Pack
     - Backpack
     - Crowbar
     - Hammer
     - 10 Pitons
     - 10 Torches
     - Tinderbox
     - 10 days of Rations
     - Waterskin
     - 50ft Hempen rope
   - Thievs' tools
     - Small file
     - Lock picks
     - Small mirror mounted on a metal handle
     - Set of narrow bladed scissors
     - Pair of pliers
** OTHER PROFICIENCIES & LANGUAGES
   - Armor
     - Light Armor
     - Medium Armor
     - Shields
   - Weapons
     - Simple Weapons
     - Martial Weapons
   - Languages
     - Sylvan
     - Elven
     - Draconic
     - Common
     - Gnome
     - Halfling
     - Dwarvish
   - Tools
     - Thievs' tools
* DESCRIPTION
** PHYSICAL ATTRIBUTES
   | AGE | HEIGHT | WEIGHT    | EYES | SKIN         | HAIR |
   |-----+--------+-----------+------+--------------+------|
   |  17 | 7' 6"  | 2,216 lbs | Gold | Brass scales | None |
** CHARACTER APPEARANCE
   Brass scaly centaur with wings, claws and the head of a dragon
** ALLIES & ORGANIZATIONS
*** NAME
** ADDITIONAL FEATURES & TRAITS
** CHARACTER BACKSTORY
*** Origin
    Because he was half dragon, he was abandoned at birth. He was able to
    survive partly because of how fast centaurs mature and because of his
    extra strength and other natural abilities as a centaur half dragon.

    He hates dragons because *they* are the reason that he is the way that he
    is and therefore the reason that he was abandoned.

    He was given no name at birth so he assumed the name of the first
    dragon that he killed as a symbol of his status as a dragonslayer.

    Because he is hated, feared and shunned by his own kind, he treats
    any companions and friends who do stay like real family and will
    do anything to protect them.
** TREASURE
* SPELLS (wisdom)
** Hail of Thorns
   | Lvl | Casting Time   | Range | Components | Duration                      |
   |-----+----------------+-------+------------+-------------------------------|
   |   1 | 1 Bonus Action | Self  | V          | Concentration, Up to 1 minute |

   The next time you hit a creature with a ranged weapon attack before the
   spell ends, this spell creates a rain of thorns that sprouts from your
   ranged weapon or ammunition. In addition to the normal effect of the attack,
   the target of the attack and each creature within 5 feet of it must make a
   Dexterity saving throw. A creature takes 1d10 piercing damage on a failed
   save, or half as much damage on a successful one.
*** At Higher Level
    If you cast this spell using a spell slot of 2nd level or higher, the
    damage increases by 1d10 for each slot level above 1st (to a maximum of 6d10).
** Hunter's Mark
   | Lvl | Casting Time   | Range | Components | Duration                    |
   |-----+----------------+-------+------------+-----------------------------|
   |   1 | 1 Bonus Action | 90ft  | V          | Concentration, Up to 1 hour |

   You choose a creature you can see within range and mystically mark it as your quarry.
   Until the spell ends, you deal an extra 1d6 damage to the target whenever you hit it
   with a weapon attack, and you have advantage on any Wisdom (Perception) or
   Wisdom (Survival) check you make to find it. If the target drops to 0 hit points
   before this spell ends, you can use a bonus action on a subsequent turn of yours
   to mark a new creature.
*** At Higher Level
    When you cast this spell using a spell slot of 3rd or 4th level, you can
    maintain your concentration on the spell for up to 8 hours.
    When you use a spell slot of 5th level or higher, you can maintain your
    concentration on the spell for up to 24 hours.
* Nugget (Pseudodragon)
  Aurus found Nugget curled up and injured in the bend of a river in a forrest that had
  just been destroyed by the fire of a red dragon. Aurus thought that it was a baby red dragon
  and was about to kill it -partially to put it out of its misery and partially out of hatred
  for dragons- but when it seemed to mature to be a baby anything, he took a closer look and
  realized that it was actually a pseudodragon.

  Aurus took pity on him because his life was also just destroyed by the pointless squabbles
  of the draggons (this particular case was actually because a blue draggon looked at a red
  dragon funey). Aurus took him into his care (getting stung by the frightened pseudodragon
  in the process) and nursed him back to health.

  He afectionally named him Nugget because he was clutching an unrefined gold nugget like
  a dragon's hoard.

  Nugget now rides proudly on Aurus's shoulder wherever he goes. In most battles Nugget stays
  at a safe distance, keeping a watchful eye on the battle and uses his telepathy to warn Aurus
  of any unseen danger but will also stay close to share his magic resistance if they are
  fighting magic users.

  After years of fighting battles and surviving together, Nugget entrusted Aurus with his
  nugget (likely in part so that he could finally have his claws free but Nugget will never
  admit it) which Aurus had set in a thick gold chain which he wears around his neck.
** HEALTH AND ARMOR
   | Armor Class | Land Speed | Air Speed |
   |-------------+------------+-----------|
   |          13 |         15 |        60 |
** STATS
   |     | STRENGTH | DEXTERITY | CONSTITUTION | INTELLIGENCE | WISDOM | CHARISMA |
   |-----+----------+-----------+--------------+--------------+--------+----------|
   | VAL |        6 |        15 |           13 |           10 |     12 |       10 |
   | MOD |       -2 |        +2 |           +1 |            0 |     +1 |        0 |

   | \check | +4 | Stealth (dex)         |
   | \check | +3 | Perception (wis)      |

   | 13 | PASSIVE WISDOM (PERCEPTION) |
** ATTACKS & SPELLCASTING
*** Bite
    - +4 to hit
    - reach 5ft
    - 4 (1d4 + 2) piercing damage
*** Sting
    - +4 to hit
    - reach 5ft
    - 4 (1d4 + 2) piercing damage
    - Target must succeed on a DC 11 Constitution saving throw or become
    poisoned for 1 hour. If the saving throw fails by 5 or more, the target
    falls unconcious for the same duration, or until it takes damage or another
    creature uses an action to shake it awake.
** FEATURES & TRAITS
   - Blindsight 10ft
   - Darkvision 60ft
   - *Keen Senses* Has advantage on Wisdom (perception) checks that rely on sight, hearing, or smell
   - *Magic Resistance* Has advantage on saving throws against spells and other magical effects.
     - Effect transfere to Aurus when he is within 10ft
   - *Limited Telepathy* Can magically communicate simple ideas, emotions, and images telepathically
     with any creature within 100ft of it that can understand a language.
   - *Familiar* Aurus can sense what Nugget senses as long as they are within 1 mile of each other.
** Languages
   Understands Common and Draconic but can't speak
* Dice

#+begin_src elisp
  (roll 100 1)
#+end_src

#+begin_src elisp
  (nd4 4)
#+end_src

#+begin_src elisp
  (nd6 2)
#+end_src

#+begin_src elisp
  (nd10 1)
#+end_src

#+begin_src elisp
  (nd12 1)
#+end_src

#+begin_src elisp
  (nd20 1)
#+end_src

#+begin_src elisp
  (nd100 1)
#+end_src
